//@version=5
indicator("Hacim Toplamı", overlay=false)

mum_sayisi = input.int(60, title="Mum Sayısı", minval=1)

hacim_toplam = 0.0
for i = 0 to mum_sayisi - 1
    if close[i] > open[i]
        hacim_toplam := hacim_toplam + volume[i]
    else if close[i] < open[i]
        hacim_toplam := hacim_toplam - volume[i]
    else
        hacim_toplam := hacim_toplam

hesaplanan_deger = hacim_toplam

plot(hesaplanan_deger, color=color.new(color.blue, 0), linewidth=2, title="Hacim Toplamı")

hline(0, "Sıfır Çizgisi", color=color.gray, linestyle=hline.style_dashed)
